services:
  - type: web
    name: bark-tts-service
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt && pip install -e ."
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        value: 10000 